name: Build Flutter Windows Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get
        working-directory: . 

      - name: Analyze code
        run: flutter analyze
        working-directory: .

      - name: Build Windows Release
        run: flutter build windows --release
        working-directory: .

      - name: Zip build output
        run: |
          Compress-Archive -Path build\windows\runner\Release\* -DestinationPath flutter_windows_release.zip
        shell: pwsh
        working-directory: .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-windows-release
          path: flutter_windows_release.zip
          retention-days: 90
